"use client";
import { useState } from "react";
import { FolderKanban, Mail, MoreHorizontal, Plus, Users } from "lucide-react";
import { Sidebar } from "@/components/sidebar";
import { Dashboard } from "@/components/dashboard";
import { Library } from "@/components/library";
import { Analysis, DetailModal, UploadModal } from "@/components/modals";
import type { Asset } from "@/lib/data";
type Page = "dashboard" | "library" | "projects" | "team" | "settings";
const projectData=[ ["Mafia","428 assets","David, Sofia, 8 more","photo-1511818966892-d7d671e672a2"], ["Doomsday","319 assets","David, Theo, 5 more","photo-1500534623283-312aade485b7"], ["Journey to the West","287 assets","Sofia, Li, 6 more","photo-1519608487953-e999c86e7455"], ["School","214 assets","David, Maya, 4 more","photo-1518005020951-eccb494ad742"] ];
function Projects(){return <div className="mx-auto max-w-[1400px] p-5 pt-20 lg:p-8"><header className="flex justify-between"><div><h1 className="text-2xl font-semibold">My Projects</h1><p className="mt-1 text-sm text-slate-500">Organize assets around your productions.</p></div><button className="button"><Plus size={16}/>New project</button></header><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{projectData.map(([n,count,m,img])=><div className="panel overflow-hidden" key={n}><img src={`https://images.unsplash.com/${img}?auto=format&fit=crop&w=700&q=80`} alt="" className="h-36 w-full object-cover"/><div className="p-4"><div className="flex justify-between"><h2 className="font-semibold">{n}</h2><MoreHorizontal size={17} className="text-slate-400"/></div><p className="mt-2 text-sm text-slate-500">{count}</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><span className="grid h-6 w-6 place-items-center rounded-full bg-blue-100 text-blue-600"><Users size={12}/></span>{m}</div></div></div>)}</div></div>}
function Team(){const people=[["David Chen","david@novastudio.co","Owner","Apr 12, 2024"],["Sofia Martin","sofia@novastudio.co","Editor","May 03, 2024"],["Theo Williams","theo@novastudio.co","Editor","Jun 18, 2024"],["Maya Singh","maya@novastudio.co","Viewer","Jul 05, 2024"]];return <div className="mx-auto max-w-[1100px] p-5 pt-20 lg:p-8"><header className="flex justify-between"><div><h1 className="text-2xl font-semibold">Team</h1><p className="mt-1 text-sm text-slate-500">Manage your workspace members and access.</p></div><button className="button"><Mail size={16}/>Invite member</button></header><div className="panel mt-7 overflow-hidden"><div className="grid grid-cols-[1.6fr_1.7fr_.7fr_1fr] gap-3 border-b bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400"><span>Member</span><span>Email</span><span>Role</span><span>Joined</span></div>{people.map((p,i)=><div className="grid grid-cols-[1.6fr_1.7fr_.7fr_1fr] items-center gap-3 border-b px-5 py-4 text-sm last:border-0" key={p[1]}><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-900 text-xs text-white">{p[0].split(" ").map(x=>x[0]).join("")}</span><b>{p[0]}</b></div><span className="truncate text-slate-500">{p[1]}</span><span className="text-slate-600">{p[2]}</span><span className="text-slate-500">{p[3]}</span></div>)}</div></div>}
export default function App(){const [page,setPage]=useState<Page>("dashboard");const [asset,setAsset]=useState<Asset|null>(null);const [upload,setUpload]=useState(false);const [analysis,setAnalysis]=useState(false);const content=page==="dashboard"?<Dashboard openAsset={setAsset} goLibrary={()=>setPage("library")} upload={()=>setUpload(true)}/>:page==="library"?<Library openAsset={setAsset} upload={()=>setUpload(true)}/>:page==="projects"?<Projects/>:page==="team"?<Team/>:<div className="p-12">Settings</div>;return <main className="flex min-h-screen"><Sidebar page={page} setPage={setPage}/><div className="min-w-0 flex-1">{content}</div>{asset&&<DetailModal asset={asset} close={()=>setAsset(null)}/>} {upload&&<UploadModal close={()=>setUpload(false)} complete={()=>{setUpload(false);setAnalysis(true)}}/>}{analysis&&<Analysis close={()=>setAnalysis(false)}/>}</main>}
