export type AssetType = "Characters" | "Scenes" | "Props" | "Wardrobe" | "Creatures" | "Vehicles";
export type AssetStatus = "Ready" | "Review" | "Draft" | "Archived";
export type Asset = { id: number; name: string; type: AssetType; image: string; tags: string[]; status: AssetStatus; project: string; used: number; created: string; uploadedBy: string };
const images = [
  "photo-1560250097-0b93528c311a", "photo-1568602471122-7832951cc4c5", "photo-1511818966892-d7d671e672a2", "photo-1504707748692-419802cf939d", "photo-1500534623283-312aade485b7", "photo-1519608487953-e999c86e7455", "photo-1544717305-2782549b5136", "photo-1518005020951-eccb494ad742", "photo-1542291026-7eec264c27ff", "photo-1489824904134-891ab64532f1", "photo-1518173946687-a4c8892bbd9f", "photo-1534972195531-d756b9bfa9f2"
];
const names: [string, AssetType, string[], AssetStatus, string][] = [
 ["Mafia Boss", "Characters", ["Mafia", "Male", "Black Suit", "Powerful"], "Ready", "Mafia"], ["Young Woman", "Characters", ["Female", "Modern", "Portrait", "Realistic"], "Ready", "Doomsday"], ["Police Officer", "Characters", ["Uniform", "Male", "Modern"], "Review", "Mafia"], ["Desert Scout", "Characters", ["Explorer", "Desert", "Future"], "Ready", "Doomsday"], ["Mafia Office at Night", "Scenes", ["Dark", "Office", "Mafia", "Night"], "Ready", "Mafia"], ["Old Warehouse", "Scenes", ["Industrial", "Abandoned", "Dark"], "Review", "Mafia"], ["Modern Apartment", "Scenes", ["Interior", "Modern", "Daylight"], "Ready", "School"], ["Desert Camp", "Scenes", ["Desert", "Camp", "Sunset"], "Draft", "Doomsday"], ["Black Axe", "Props", ["Weapon", "Metal", "Vintage", "Wood"], "Ready", "Mafia"], ["Military Rifle", "Props", ["Weapon", "Military", "Modern"], "Review", "Doomsday"], ["Leather Briefcase", "Props", ["Business", "Leather", "Mafia"], "Ready", "Mafia"], ["Ancient Scroll", "Props", ["Paper", "Ancient", "Chinese"], "Ready", "Journey to the West"], ["Black Tailored Suit", "Wardrobe", ["Formal", "Black", "Mafia"], "Ready", "Mafia"], ["School Uniform", "Wardrobe", ["Uniform", "Youth", "Modern"], "Ready", "School"], ["Desert Jacket", "Wardrobe", ["Utility", "Sand", "Future"], "Draft", "Doomsday"], ["Silk Robe", "Wardrobe", ["Ancient", "Chinese", "Gold"], "Ready", "Journey to the West"], ["Shadow Wolf", "Creatures", ["Wolf", "Dark", "Fantasy"], "Ready", "Doomsday"], ["Golden Dragon", "Creatures", ["Dragon", "Mythical", "Chinese"], "Review", "Journey to the West"], ["Desert Falcon", "Creatures", ["Bird", "Desert", "Wildlife"], "Ready", "Doomsday"], ["Stone Golem", "Creatures", ["Rock", "Fantasy", "Ancient"], "Archived", "Journey to the West"], ["Vintage Sedan", "Vehicles", ["Car", "Vintage", "Black", "Mafia"], "Ready", "Mafia"], ["Police Cruiser", "Vehicles", ["Car", "Police", "Modern"], "Ready", "School"], ["Desert Rover", "Vehicles", ["Truck", "Desert", "Future"], "Review", "Doomsday"], ["Flying Lantern", "Vehicles", ["Fantasy", "Ancient", "Chinese"], "Ready", "Journey to the West"], ["Night Club Entrance", "Scenes", ["Neon", "Mafia", "Night"], "Ready", "Mafia"], ["Street Vendor", "Characters", ["Male", "Urban", "Modern"], "Ready", "School"], ["Brass Pocket Watch", "Props", ["Vintage", "Gold", "Mafia"], "Draft", "Mafia"], ["Combat Boots", "Wardrobe", ["Military", "Black", "Modern"], "Ready", "Doomsday"], ["White Tiger", "Creatures", ["Tiger", "Fantasy", "White"], "Ready", "Journey to the West"], ["Armored Van", "Vehicles", ["Military", "Vehicle", "Black"], "Ready", "Doomsday"]
];
export const assets: Asset[] = names.map(([name, type, tags, status, project], i) => ({ id: i + 1, name, type, tags, status, project, used: (i * 7) % 39 + 1, created: i < 8 ? "Today" : `${Math.floor(i / 3) + 1} days ago`, uploadedBy: i % 2 ? "David Chen" : "Sofia Martin", image: `https://images.unsplash.com/${images[i % images.length]}?auto=format&fit=crop&w=800&q=82` }));
export const categories = ["Characters", "Scenes", "Props", "Wardrobe", "Creatures", "Vehicles"] as AssetType[];
